### ISSUE TITLE
dates and obs order

### ISSUE THREAD

**Issue by mmazzolini** [ealonsogzl/MuSA#11]
Hi @ealonsogzl..
I'm designing my first joint assimilation experiments and I wanted to ask something about dates and obs ordering.

In the config.py file, I read this note:

# Note: Dates and obs files will be sorted internally. Ensure the alphabetical
# order of the obs files fits the list of dates (dates_obs)

From this, I get that the alphabetical order of the files in the nc_obs_path should correspond to the list of dates.
But, in the get_dates_obs() function, there's a dates_obs.sort() [line 124]

Am I wrong or that should be removed?

I explain you my case: the list of my obs files (alphabetically-sorted) is this:

 '/fSCA_20200405.nc',
 '/fSCA_20200503.nc',
 '/fSCA_20200518.nc',
 '/fSCA_20200520.nc',
 '/obs_20200205_10_20m.nc'

so all the files with fSCA come before.

Should I just name the observations with just the date and have also the obs dates listed cronologically? (in that case we have to update the note..

or should we keep the note and remove the dates_obs.sort() line? 
To my understanding, they are clashing (but maybe there's something else in the code I didn't understand).

BTW that .sort() is not there in the case when the user inputs a file..
 

Cheers,
Marco.

**Comment by ealonsogzl** [comment]
The documentation should be improved, at least on these critical points.

In case of a joint assim, it would be best to have each observation in a variable within the same netcdf files. 

This ensures that the chronological order is always respected. In case one of the variables is not present in one of the timesteps but the other one is, that is not a problem (if it has been saved as a NaN value). 

A practical example to clarify. Let's imagine you want to assimilate 2 snow depth observations (HS) on the dates 23/1 and 2/4 together with 1 FSCA observation on 25/05. You should generate 3 files (one per date), with 2 variables (HS & FSCA):

```
obs_20200123.nc  #  HS = float & FSCA= NaN
obs_20200402.nc  #  HS = float & FSCA= NaN
obs_20200525.nc  #  HS = NaN & FSCA= float
```

By the way, it is not strictly necessary to have a file for each observed date, in principle it can be a single netcdf with several variables (one per observed variable) as long as the time dimension (common for al the observed variables) is properly configured.

Maybe we can think of a more intuitive system?

**Comment by mmazzolini** [comment]
I see.

To me, it feels a bit convoluted that every observation file must have all the variables you want to assimilate.
It would be more intuitive to me if every file just contains one variable..

I try to commit a couple of changes that allow this in the afternoon, but you'll have to judge if that's fine :)

**Comment by ealonsogzl** [comment]
Having all variables in all files is not a problem. netcdf compression compensates for the hypothetical waste of physical memory, because if there are no observations in a variable all values are the same (nan value), which can be compressed very easily. netcdf is very convenient for these things, otherwise it would probably be more convenient to use another format.

In case you have many observations of different variables, this is the way to keep everything under control. Otherwise you would be very prone to make mistakes when preparing the forcing because you would have different files, each one with a different number of variables (+ their corresponding error variables), a chaos.

The question is whether to start using the time dimension dates within the netcdf, or to continue with the current strategy.
The current strategy of entering observation dates 'by hand' is simply too easy to maintain, and avoids problems with dates within netcdf, which will give problems if the files are not always created with the same conventions. Moreover, it is easy to generate a csv with dates with any tool.

**Comment by mmazzolini** [comment]
I see that .netcdf compresses this very well..
On the other hand, I find it quite user-friendly to have the possibility to just have one observation per file (without the other variables filled with NaN)

I'll commit the modifications to allow that and make a PR with that and you tell me what you think.
(I used some try/except blocks so it might not be the best.. so totally fine if you think it's not okay)
