### ISSUE TITLE
Small change in the last PR

### ISSUE THREAD

**Issue by ealonsogzl** [ealonsogzl/MuSA#16]
Hey  @mmazzolini,

I wonder if the way we implemented the latest changes might be a bit error prone to config.

In particular `if var_to_prop = False -> than all the var_to_assim are spatially propagated` 

This breaks the logic a bit, because if something is `False`, the natural way of thinking is that it is deactivated.

I propose that var_to_prop should always be a list (not a boolean), so that the variables in that list are the ones that are propagated. If `var_to_prop == var_to_assim` all variables are propagated, but if `var_to_prop = []` (i.e. empty list), nothing is spatially propagated. 

Do you think you could implement it? You are more familiar with this last PR than I am.

**Comment by mmazzolini** [comment]
Hi @ealonsogzl..

I see your point. I think should be possible to change that. 

We can leave in the default configuration var_to_prop = var_to_assim so that by default all the variables are propagated as it was before.

I think without the false option the code will be actually cleaner, will try to do a PR today.

**Comment by ealonsogzl** [comment]
thanks!
